### ISSUE TITLE
ocp-browser: allow search by type signature

### ISSUE THREAD

**Issue by UnixJunkie** [OCamlPro/ocp-index#110]
For example: "'a list -> 'a" is my query.
That would be a killer feature!
Bonus points: my type signature is incorrect but ocp-browser shows me the nearest it can find; rank-ordered by decreasing similarity.

**Comment by Drup** [comment]
You already requested that feature: https://github.com/OCamlPro/ocp-index/issues/73 :)

**Comment by UnixJunkie** [comment]
yes, and still not there. ;)

**Comment by Drup** [comment]
@UnixJunkie You are welcome to contribute a working diophantine equation solver for https://github.com/Drup/dowsing :)

**Comment by UnixJunkie** [comment]
Sorry, I am not a computer science researcher.
