### ISSUE TITLE
ocp-index depends on lambda-term

### ISSUE THREAD

**Issue by reynir** [OCamlPro/ocp-index#111]
When pinning ocp-index to dev-repo I get the following error when upgrading packages:
```
### stderr ###
# Error: External library "lambda-term" not found.
# -> required by "src/jbuild (context default)"
# Hint: try: jbuilder external-lib-deps --missing -p ocp-index @install
```
The package lambda-term was installed, but was removed (temporarily) during the upgrade. Looking at the opam files and the jbuild file I can't tell why jbuilder is looking at the dependencies for browserMain.

**Comment by Drup** [comment]
I'm quite confused by that one. As far as I see, ocp-index does not depend on lambda-term, even through transitive dependencies. I'm going to close. Feel free to re-open if you have more detail/a principled way to reproduce.

**Comment by reynir** [comment]
It's ocp-browser in the same repo that depends on lambda-term. Somehow this confuses jbuilder to expect ocp-index to depend on lambda-term. I'm on my way out of the door now so I can't reproduce right now. Please remind me!

**Comment by Drup** [comment]
That would be a big jbuilder fail. :)
