### ISSUE TITLE
4.07 support 

### ISSUE THREAD

**Issue by copy** [OCamlPro/ocp-index#117]
Currently, on `4.07.0+beta2+flambda`:

```
# File "libs/indexBuild.ml", line 413, characters 30-40:
# Error: Unbound record field Ident.name
#     ocamlopt libs/.indexLib.objs/indexBuild.{cmx,o} (exit 2)
# (cd _build/default && /media/samsung/opam2/4.07.0+beta2+flambda/bin/ocamlopt.opt -w -40 -g -I libs/.indexLib.objs -I /media/samsung/opam2/4.07.0+beta2+flambda/lib/ocaml/compiler-libs -I /media/samsung/opam2/4.07.0+beta2+flambda/lib/ocp-indent/lexer -I /media/samsung/opam2/4.07.0+beta2+flambda/lib/ocp-indent/utils -no-alias-deps -o libs/.indexLib.objs/indexBuild.cmx -c -impl libs/indexBuild.pp.ml)
# File "libs/indexBuild.ml", line 413, characters 30-40:
# Error: Unbound record field Ident.name
```

**Comment by copy** [comment]
Quick follow-up: The master branch works on 4.07, but the standard library modules (Array, Unix, …) are only accessible as `Stdlib.Foo`, not `Foo` directly.

**Comment by pmetzger** [comment]
I was curious if there was any change in status?

**Comment by mseri** [comment]
Is it possible to release a new version from the current master?

**Comment by ygrek** [comment]
please tag new release

**Comment by pmetzger** [comment]
Just a side note: perhaps this would be a good candidate for OCaml-community? It would allow more people to have the ability to make a release.

**Comment by lindig** [comment]
You can pin the master branch and install it without a release.

```
opam pin add ocp-index https://github.com/OCamlPro/ocp-index.git
```

**Comment by mseri** [comment]
It is still annoying that this is thr only way to get a version working with 4.07 when the current masterseems to be ready fro release

**Comment by XVilka** [comment]
This one is a good candidate to move into OCaml-community IMHO.

**Comment by pmetzger** [comment]
@XVilka If you can convince the maintainers, it would be accepted.

**Comment by AltGr** [comment]
Sorry for the lag... will get to it shortly ^^

**Comment by XVilka** [comment]
So can be closed now?

**Comment by pmetzger** [comment]
I think someone should probably update the OPAM package before it gets closed, but the side that needs to be done in this repository seems complete.

**Comment by pmetzger** [comment]
Ah, it looks like it is indeed now in opam, though oddly installing it seems to require downgrading ocp-pp...

**Comment by copy** [comment]
Closing as fixed in opam. Cheers @AltGr.
