### ISSUE TITLE
feature request: search by type signature

### ISSUE THREAD

**Issue by UnixJunkie** [OCamlPro/ocp-index#121]
http://www.dicosmo.org/ResearchThemes/ISOS/ISOShomepage.html

I wonder if the caml code in there could be ported and work for OCaml.

**Comment by AltGr** [comment]
I'd definitely like to have this feature :)
The main reason I haven't done it as of now is that it kind of contradicts the base design of ocp-index, which searches definitions by prefix, loading the module signatures lazily: for a global search, you would need to load _all_ installed cmi/cmtis before anything else.

But even for searching within a single module, e.g. in `ocp-browser` and for big modules, that could be quite useful. ("So now tell me the functions that I can use to build your abstract type `t`, please")

**Comment by UnixJunkie** [comment]
maybe a command-line version of ocp-index would do then.
But it's true it's cool when results are updated on the fly.

**Comment by Drup** [comment]
Duplicated of https://github.com/OCamlPro/ocp-index/issues/110, which was already a duplication, all from you.

I've a very-WIP prototype on https://github.com/Drup/dowsing but in the meantime 1) it's much harder than you think 2) it'll take time 3) I'm not very fond of the passive agressive approach of repeating your bug report on a regular basis while the initial answer is "it's complicated and we don't have time".

**Comment by UnixJunkie** [comment]
I don't think it's that complicated.
I think a fuzzy search is enough in 99% of user search cases.
I'm tired of not having a 100% working and maintained hoogle for OCaml that
everybody would switch to because it would be working so good.
Hoogle in Haskell is a dramatic performance booster!

**Comment by UnixJunkie** [comment]
Sometimes, you look for a perfect solution, there is one but it is very difficult to reach.
While a fuzzy solution to the same problem is much easier (as in 20% of the effort only) and would be way better than nothing-really-working (our current state).
