### ISSUE TITLE
Is ocp-browser working with ocaml-4.07.0? 

### ISSUE THREAD

**Issue by UnixJunkie** [OCamlPro/ocp-index#127]
Hello,
I have OCaml version 4.07.0 and ocp-browser 1.1.7 and ocp-index 1.1.7.
When I launch ocp-browser, nauthing happens.

```
# which ocp-browser 
/home/berenger/.opam/ocaml-base-compiler.4.07.0/bin/ocp-browser
# ocp-browser
# ocp-browser --help
```
The strace is here:
https://gist.github.com/UnixJunkie/13d62fd155b15f2ff4dbc8abe1ae9d6d

**Comment by UnixJunkie** [comment]
I start to suspect opam is the culprit.
I have opam-2.0.2

**Comment by UnixJunkie** [comment]
ocp-index.1.1.5 gives me a working ocp-browser

**Comment by UnixJunkie** [comment]
I'll stick to this one for the time being

**Comment by Drup** [comment]
Solved in 1.1.8

**Comment by UnixJunkie** [comment]
I still need to install an ocp-index.1.1.5 to get a working ocp-browser.

**Comment by UnixJunkie** [comment]
ocp-index 1.1.6 and ocp-index.1.1.7 make for a broken ocp-browser (ocp-browser exists just after start)

**Comment by UnixJunkie** [comment]
This is the working config I have currently:
* ocp-index.1.1.5
∗ ocp-browser.1.0.0
∗ user-setup.0.7

**Comment by Drup** [comment]
That's due to [yet another bug](https://github.com/ocaml/dune/issues/1811).
