### ISSUE TITLE
ocp-browser not building in opam on 4.08.1 with up to date lambda-term

### ISSUE THREAD

**Issue by pmetzger** [OCamlPro/ocp-index#137]
Howdy! Under 4.08.1, ocp-browser doesn't install in opam against the latest version of lambda-term. I think the issue is that it's constrained to an older version.

**Comment by UnixJunkie** [comment]
I confirm this: ocp-browser is not co-installable with utop under OCaml-4.08.1.
I think a new release in opam-repository for ocp-browser would be nice.
In the meantime, pinning ocp-browser to its dev repo works fine.

**Comment by Drup** [comment]
Solved, and release is on its way!
