### ISSUE TITLE
ocp-index-grep-expr

### ISSUE THREAD

**Issue by UnixJunkie** [OCamlPro/ocp-index#69]
Feature request for a new emacs command: it would interactively ask an expression to grep
instead of using what is under the cursor

**Comment by AltGr** [comment]
I use `M-x grep` (and change the command to `ocp-grep`) for that :)
A shortcut could still be useful though

**Comment by AltGr** [comment]
I got tired of `M-x grep` and wrote a better interface: `C-c /` (`ocp-index-grep`) now prompts for a symbol to grep for, but automatically set the default to the (qualified) symbol under point. I think it's the best compromise. It also allows fixing the symbol when ocp-index doesn't get exactly what you want.

The command also allows for grepping within literal strings, by enclosing the query in double quotes.

This is in 9b4b53d31361ab77173ca06102c325b98f5a69aa
