### ISSUE TITLE
Completion through functor signatures

### ISSUE THREAD

**Issue by Drup** [OCamlPro/ocp-index#70]
There is still an issue when looking up a signature through a "functor signature". An example of such declaration is in Tyxml, in the module `Html5`:
```ocaml
module M : Html5_sigs.Make(Xml)(Svg.M).T
```

`ocp-index complete Html5.M` doesn't returns anything.

**Comment by AltGr** [comment]
What version ? I get
```
% ocp-index complete Html5.M
Html5.M module Html5_sigs.Make(Xml)(Svg.M).T
    Concrete implementation of HTML5 typesafe constructors
Html5.Make_printer module
  functor (O : Xml_sigs.Output) ->
    sig
      val print_list : ?encode:(string -> string) -> 'a M.elt list -> O.out
      val print :
        ?encode:(string -> string) -> ?advert:string -> M.doc -> O.out
    end
    Parametrized stream printer for HTML5 documents
```

Then I do have a few experimental patches locally, maybe they are worth something after all ;)
(`ocp-index complete Html5.M.` returns all the elemements in `Html5_sigs.MakeWrapped.T.`)

**Comment by Drup** [comment]
Arg, typo in the bug report. I meant `ocp-index complete Html5.M.` with the dot at the end !



> `ocp-index complete Html5.M.` returns all the elemements in `Html5_sigs.MakeWrapped.T.`

Then your patch are definitely worth something, where are they ? :]

**Comment by AltGr** [comment]
Just pushed my latest patches to the 4.02 (and 4.03) branches. Sorry for the lag!

**Comment by Drup** [comment]
weee, it's working ♥
