### ISSUE TITLE
ocp-browser (and ocp-index, I presume) is slow to start

### ISSUE THREAD

**Issue by Drup** [OCamlPro/ocp-index#71]
I have a rather big opam local install (and I keep all the .cmt ...) but ocp-browser is starting to get really slow to start now. I think it's worse since you push the last few patches.

Do you have ideas what the issue is ? I can try to profile properly when I get some time.

**Comment by Drup** [comment]
After some tests I think the issue is because we try to get the completion for the empty string at the start of ocp-browser. On my machine, it takes almost a full second.

The completion for non-empty string is still quite fast.

**Comment by AltGr** [comment]
I'll need to get my head in that patch again to remember what it does ; it may not be properly optimised. On the empty string, you normally only get module names and Pervasives: the time should be that of listing all files, might take a short while with many directories on a slow hdd, but even in that case should become instant on second run.

Indeed it seems that `ocp-index complete ""` loads _all_ cmts (setting `OCP_DEBUG` to 1 makes it list the files it loads), which it wasn't doing before. It's a bug :)

Thanks!

**Comment by AltGr** [comment]
The culprit for that specific bug is actually 522b941 and is due to the sorting. On it.

**Comment by AltGr** [comment]
Sorting results by source file was a bad idea. Now fixed :)

The latest patches might have made loading slower, though

**Comment by Drup** [comment]
Ah! It's now much much faster to load. Thanks! ♥
