### ISSUE TITLE
ocp-browser feature request: allow showing corresponding ocamldoc upon some keystroke

### ISSUE THREAD

**Issue by UnixJunkie** [OCamlPro/ocp-index#72]
ocp-browser is fantastic.
It could be great if it was also possible, upon some keystroke (like 'd' for doc?), to show
the corresponding ocamldoc entry.

**Comment by Drup** [comment]
`space` ;)

When it's available only (when the .cmt/d are accessible) unfortunately.

**Comment by UnixJunkie** [comment]
How to install them ?
Even List.length from the stdlib doesn't show anything with the space key.

**Comment by Drup** [comment]
@AltGr I think there is a bug in the lookup for cmt. If I keep the build dir, I get the documentation but not if it's installed in the lib dir.

**Comment by Drup** [comment]
(reproducible on 4.02.3 with the stdlib)

**Comment by AltGr** [comment]
It may be an issue with locating the doc in cmti format on 4.02.3, because the cmti is properly loaded:
```
[lg@agaric ~]% opam config exec --switch 4.02.3 ocp-index print List.map "%f %l %d"
/home/lg/.opam/4.02.3/lib/ocaml/list.cmti list.ml:53:8 
[lg@agaric ~]% opam config exec --switch 4.02.1 ocp-index print List.map "%f %l %d"
/home/lg/.opam/4.02.1/lib/ocaml/list.cmi <no location information> 
```

**Comment by UnixJunkie** [comment]
# ocp-index print List.map "%f %l %d"
    /home/berenger/.opam/4.01.0/lib/ocaml/list.cmi <no location information>

**Comment by AltGr** [comment]
I meant within the 4.02.3 cmti format itself, ocp-index may fail to grab the doc ; files seem to be located ok.

**Comment by AltGr** [comment]
I've implemented lookup of doc using the new 4.02.3 format, which is better -- and 4.02.3 doesn't ship cmts with the raw comments anymore, which is why it failed. For 4.03 we'll probably be able to drop the complex comment-associating code based on positions :)

 New release 1.1.3 is underway!

**Comment by UnixJunkie** [comment]
Thanks !

**Comment by Drup** [comment]
Nice. Thanks @AltGr
