### ISSUE TITLE
ocp-browser feature request: lookup by type signature

### ISSUE THREAD

**Issue by UnixJunkie** [OCamlPro/ocp-index#73]
For example: 'a -> 'a
It would be nice if an approximate search is done in case the original query yields no results.

**Comment by Drup** [comment]
It's something I have in my todo list, yes. My plan was to investigate how it's done in ocamlscope first.

**Comment by AltGr** [comment]
ocp-index stores the types using `Outcometree.out_type` (same as used by the toplevel for output). It should be fairly doable to:
* convert the pattern to `out_type`
* write a function that finds matches of one `out_type` within another
* apply that to filter a sub-trie (we already have everything for that)

**Comment by AltGr** [comment]
(of course, we don't have a database, so you'll have to wait for all the interfaces you want to search into to load. Well, we could always try to improve on that later on, although that gets somehow beyond the scope of ocp-index, why not)

**Comment by Drup** [comment]
@AltGr The other difficulty is to find a good unification function. The one in ocamlscope is not good at all.

**Comment by UnixJunkie** [comment]
I know ocamlscope and it is not good enough.
I am not sure you should try to get any inspiration from it.

**Comment by Drup** [comment]
I started working on this in a separate project. It's definitely out of scope for ocp-index/browser and requires quite a bit of machinery. I think we can close this.
