### ISSUE TITLE
feature request: ocp-grep --def identifier

### ISSUE THREAD

**Issue by UnixJunkie** [OCamlPro/ocp-index#81]
looks for the definition of the identifier, rather than all occurrences.
It would be to help me when merlin fails on me or I don't even have merlin configured in a project.

**Comment by nojb** [comment]
Hi, note that you can already get this information by doing `ocp-index locate <identifier>`.

**Comment by Drup** [comment]
This is clearly a job for ocp-index, not ocp-grep.
