### ISSUE TITLE
Make 4.03-proof release

### ISSUE THREAD

**Issue by Drup** [OCamlPro/ocp-index#84]

**Comment by Fourchaux** [comment]
for info :  
(with $ opam switch install 4.03.0+flambda & opam install ocp-index) :  
opam-version 1.2.2
os           linux
compiler     4.03.0+flambda
...
--- stderr ---
Here is an example of a value that is not matched:
Otyp_attribute (_, _)
File "src/indexBuild.ml", line 236, characters 15-30:
 Error: This pattern matches values of type 'a * 'b * 'c
        but a pattern was expected which matches values of type
          Outcometree.out_val_decl
Error:
Target _obuild/ocp-index-lib/indexBuild.cmo not built
...

**Comment by Drup** [comment]
Yes, I though the 4.03 branch was ready, but it actually isn't, see https://github.com/OCamlPro/ocp-index/pull/85

**Comment by Fourchaux** [comment]
Error still there.

See also : https://sympa.inria.fr/sympa/arc/caml-list/2016-05/msg00079.html

Any difficulty ?

**Comment by lefessan** [comment]
See https://github.com/ocaml/opam-repository/pull/6518

**Comment by lefessan** [comment]
PR was merged, ocp-index.1.1.4 is now compatible with 4.03 on OPAM. See http://opam.ocamlpro.com/builder/html/report-last.html#ocp-index

I am now working on a patch to make the code compatible with 4.01, 4.02 and 4.03

**Comment by AltGr** [comment]
@lefessan thanks!

**Comment by Fourchaux** [comment]
opam install : OK
Thank You.
