### ISSUE TITLE
ocp-browser feature request, history. 

### ISSUE THREAD

**Issue by fxfactorial** [OCamlPro/ocp-index#89]
I love ocp-browser and one thing it gives me is a good feel for an API while developing a library. 

So with nested modules, objects this becomes annoying as I'm looking up method definitions. 

Would be nice, and I assume straightforward, to have a ocp-browser history, maybe use a modifier key + up to go through history.

**Comment by Drup** [comment]
Doesn't Alt+left/right sort of solve that problem ?

**Comment by fxfactorial** [comment]
No, alt+left/right just jumped to the key word `in`

**Comment by Drup** [comment]
alt+left/right is supposed to go down the module, or to peel down one layer in the module hierarchy. If it doesn't work in OS X, then this is a lambda-term bug.
