### ISSUE TITLE
compilation failure under OCaml 4.04

### ISSUE THREAD

**Issue by gasche** [OCamlPro/ocp-index#92]
opam-builder report: <http://opam.ocamlpro.com/builder/html/ocp-index/ocp-index.1.1.4/e731404b7c60a4c13ffa76493c91b02c>

```
File "src/indexPredefined.ml", line 27, characters 6-227:
Error: Some record fields are undefined: otype_unboxed
Target _obuild/ocp-index-lib/indexPredefined.cmo not built
```

This comes from a 4.04 change to the definitions in Outcometree in the compiler sources.

**Comment by UnixJunkie** [comment]
This is problematic: the opam package doesn't install in a 4.04.0+beta1 switch then.
So, no ocp-browser for me. :(
The only tool being a production-ready version of the poor man's hoogle for ocaml ...

**Comment by UnixJunkie** [comment]
this can be tagged as a compilation problem / bug

**Comment by AltGr** [comment]
Now ported :)
Enjoy!

**Comment by UnixJunkie** [comment]
thanks!
