### ISSUE TITLE
 I wish there was an ocp-browser standalone opam package

### ISSUE THREAD

**Issue by UnixJunkie** [OCamlPro/ocp-index#95]
Cf. https://github.com/ocaml/opam-repository/issues/7302

**Comment by AltGr** [comment]
You mean, just for visibility ? It's true that `opam install ocp-index lambda-term` is not completely obvious, even though there is a small message advertising it when you install `ocp-index` alone.

**Comment by UnixJunkie** [comment]
I mean for ease of install, yes.
Maybe it could be a kind of "virtual" package and just install lambda-term in fact.
I don't know how to handle this case properly in opam (uninstall should also uninstall ocp-browser).

**Comment by AltGr** [comment]
in that case, it should really build ocp-browser, but it should be based on the lib installed by the ocp-index package. The two packages would just share the same archive.

**Comment by UnixJunkie** [comment]
I see.
Maybe the first step is to create the new opam package for ocp-browser.
Then, modify the ocp-index package to not install ocp-browser anymore.
Maybe I'll find time for the first step.
I'll let the second step to the ocp-index package maintainer.
Is it OK with you ?

**Comment by Drup** [comment]
There is an independent package now. Closing!

**Comment by UnixJunkie** [comment]
Yes, I contributed this virtual package to opam some time ago.
