### ISSUE TITLE
findlib warning: 

### ISSUE THREAD

**Issue by fxfactorial** [OCamlPro/ocp-index#97]
Just got this warning: 

findlib: [WARNING] While parsing '/Users/Edgar/.opam/objc/lib/ocp-index/META': Expected a '=' or a '(arguments,...)=' clause at line 2 position 37

**Comment by hcarty** [comment]
See #96 

I'm going to submit a PR against the opam repository today.

**Comment by fxfactorial** [comment]
Thanks!
